apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
    description: LAN airconnect
  creationTimestamp: null
  labels:
    app: airconnect
  name: airconnect
  selfLink: /apis/apps/v1/namespaces/airconnect/deployments/airconnect
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: airconnect
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        description: LAN airconnect
      creationTimestamp: null
      labels:
        app: airconnect
      name: airconnect
    spec:
      containers:
      - env:
        - name: tz
          value: Europe/Berlin
        image: marvinmarvin/docker-k8s-airconnect
        imagePullPolicy: Always
        name: airconnect
        resources: {}
        securityContext:
          privileged: true
          procMount: Default
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeName: allanon
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
