apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
    description: LAN airconnect
  creationTimestamp: null
  labels:
    app: airconnect
  name: airconnect
  selfLink: /apis/apps/v1/namespaces/airconnect/deployments/airconnect
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: airconnect
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        description: LAN airconnect
      creationTimestamp: null
      labels:
        app: airconnect
      name: airconnect
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
           - labelSelector:
               matchLabels:
                 app: airconnect
             topologyKey: kubernetes.io/hostname
      containers:
      - env:
        - name: tz
          value: Europe/Berlin
        image: marvinmarvin/docker-k8s-airconnect
        imagePullPolicy: Always
        name: airconnect
        resources:
          requests:
            cpu: "50m"
            memory: "16Mi"
          limits:
            cpu: "100m"
            memory: "32Mi"
        securityContext:
          privileged: true
          procMount: Default
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
